### ISSUE TITLE
Add all semesters to course edit dropdown

### ISSUE THREAD

**Issue by kljensen** [kljensen/yale-class-chat#21] opened 2020-03-12 03:39 UTC
The semester dropdown in the course edit view only shows the currently used semester, not the list of all semesters
<img width="1392" alt="Screen Shot 2020-03-11 at 8 35 32 PM" src="https://user-images.githubusercontent.com/73154/76484997-7083e800-63d8-11ea-9514-cc84113ec07b.png">

**Comment by nperanzi** [comment] 2020-03-12 04:55
This is by design - users should not be able to change the parent record field. Is there a use case where someone would want to change the semester for a course?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kljensen** [comment] 2020-03-12 13:22
Nick - Shouldn't I be able to change the semester of a course? Isn't it
just a foreign key? I can't think of a use case other than "shoot, I put
this in the wrong semester".

**Comment by nperanzi** [comment] 2020-03-12 19:01
You are correct that it's just a foreign key. My concern is that the valid use case you mention is far less likely than a user thinking they can simply take last year's MGT656 course, change the semester to the current one, and then use that going forward for students. This would lead to obvious issues (all old students still having write access, new students seeing all old submissions, etc.)

Regardless, I will work on a fix for this.

**Comment by nperanzi** [comment] 2020-03-15 15:20
Fixed in 707339e2fd940112a0e7d6a0d72f7211872805de

**Closed by nperanzi** 2020-03-15 15:20 UTC
Labels: bug
